2020-07-21 05:24:34,104--ERROR--->##### SSH FAILED ######
Traceback (most recent call last):
  File "/home/do/Desktop/Projects/DevOps/2_pxssh_custom-logging.py", line 38, in <module>
    ssh.login(hostname, username, password, login_timeout=5)
  File "/usr/lib/python3/dist-packages/pexpect/pxssh.py", line 432, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b" \r\nLast login: Tue Jul 21 04:22:22 2020 from 192.168.0.101\r\r\n\x1b[5nArista1>unset PROMPT_COMMAND\r\n% Invalid input\r\nArista1>PS1='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>set prompt='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>", expected: '\\[PEXPECT\\][\\$\\#] ').
2020-07-21 05:28:14,555--DEBUG--->Begin SSH to Arista
2020-07-21 05:29:06,997--ERROR--->##### SSH FAILED ######
Traceback (most recent call last):
  File "/home/do/Desktop/Projects/DevOps/2_pxssh_custom-logging.py", line 39, in <module>
    ssh.login(hostname, username, password, login_timeout=5)
  File "/usr/lib/python3/dist-packages/pexpect/pxssh.py", line 432, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b" \r\nLast login: Tue Jul 21 04:23:38 2020 from 192.168.0.101\r\r\n\x1b[5nArista1>unset PROMPT_COMMAND\r\n% Invalid input\r\nArista1>PS1='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>set prompt='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>", expected: '\\[PEXPECT\\][\\$\\#] ').
2020-07-21 05:32:51,649--DEBUG:38--->Begin SSH to Arista
2020-07-21 05:33:44,122--ERROR:58--->##### SSH FAILED ######
Traceback (most recent call last):
  File "/home/do/Desktop/Projects/DevOps/2_pxssh_custom-logging.py", line 39, in <module>
    ssh.login(hostname, username, password, login_timeout=5)
  File "/usr/lib/python3/dist-packages/pexpect/pxssh.py", line 432, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b" \r\nLast login: Tue Jul 21 04:31:35 2020 from 192.168.0.101\r\r\n\x1b[5nArista1>unset PROMPT_COMMAND\r\n% Invalid input\r\nArista1>PS1='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>set prompt='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>", expected: '\\[PEXPECT\\][\\$\\#] ').
2020-07-23 04:40:29,044--DEBUG:38--->Begin SSH to Arista
2020-07-23 04:41:22,302--ERROR:58--->##### SSH FAILED ######
Traceback (most recent call last):
  File "/home/do/Desktop/Projects/DevOps/2_pxssh_custom-logging.py", line 39, in <module>
    ssh.login("192.168.0.1", "admin", "devops")
  File "/usr/lib/python3/dist-packages/pexpect/pxssh.py", line 432, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b" \r\n\x1b[5nArista1>unset PROMPT_COMMAND\r\n% Invalid input\r\nArista1>PS1='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>set prompt='[PEXPECT]\\$ '\r\n% Invalid input\r\nArista1>", expected: '\\[PEXPECT\\][\\$\\#] ').
